### ISSUE TITLE
Wrong folder name in default config.yml

### ISSUE THREAD

**Issue by jiahao42** [Lixody/Eir#1]
https://github.com/Lixody/Eir/blob/f545b25096953ff90d7e47ff5b8e32fb547bb194/PHPAnalysis/PHPAnalysis/config.yml#L33-L35
They should be JSONSpecifications and StoredSQLProviders, takes me some time to figure out the config problem :)

**Comment by ArchiFloyd** [comment]
The config.yml file is only uploaded due to compilation issues. Originally it wasn’t part of the repository since one should do reconfiguration matching ones environment using the config file template.
